#!/bin/bash
pythonpath='/usr/local/vfastonline/vfast'
pidfile='/var/run/uwsgi'
logpath='/var/log/vfast'
lockdir='/var/lock/subsys'
lock_file_path=$lockdir/uwsgi

mkdir -pv $pidfile


function start(){
#    echo "start uwsgi web and api.........."
    if [ ! -d $logpath ];then
	mkdir $logpath
	exit
    fi

    if [ -e $lock_file_path ];then
        echo -e "\033[31mUWSGI IS ALREADY START.......\033[0m"
        exit
    fi
    cd $pythonpath
    if [ $? -eq 0 ]
    then
        /usr/local/bin/uwsgi --ini vfast.ini -d $logpath/uwsgi.log  --uid vfast --gid vfast  --pidfile $pidfile/api.pid ; return_value=$?
        if test -w "$lockdir"
        then
            touch $lock_file_path
            echo -e "\033[34mSTART SUCCESS!!!\033[0m"
        fi
        exit $return_value
    else
        echo "start uwsgi web and api failed.......permission deny!"
    fi
    
}

function stop(){
#    echo "STOP UWSGI web and api........"
    rm -rf  $lock_file_path
    pid=`ps -ef | grep uwsgi | awk '{print $2}'| head -1`
    kill -9 $pid   >/dev/null 2>&1
    if [ $? -eq 0 ];then
        rm -rf $lock_file_path
        echo -e "\033[34mSTOP UWSGI  SUCCESS!!!\033[0m"
    elif [ $? -eq 1 ];then
        echo -e "\033[34mUWSGI IS NOT RUNNING\033[0m"
    fi
}


function status(){
    if [ ! -e $lock_file_path ]
    then
        echo "UWSGI IS NOT RUNNING....."
        exit 
    else
        ps -ef | grep uwsgi | grep -v "grep"
    fi
}




case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status
    ;;
*)
    echo $"Usage: $0 {start|stop|status}"
    exit 2
esac
