# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=20, verbose_name='\u8eab\u4efd\u540d\u79f0')),
            ],
        ),
    ]
