# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('fullname', models.CharField(max_length=100, verbose_name='\u516c\u53f8\u5168\u79f0')),
                ('name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u7b80\u79f0')),
                ('trade', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u53f8\u884c\u4e1a')),
                ('scale', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u53f8\u4eba\u5458\u89c4\u6a21')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='\u516c\u53f8\u56e2\u961f\u4eae\u70b9')),
                ('forwho', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u81ea\u4e3b\u62db\u8058or\u730e\u5934\u62db\u8058')),
                ('period', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u62db\u8058\u5468\u671f')),
                ('technology_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u62db\u8058\u6280\u672f\u7c7b\u522b, java, python')),
                ('wanted_exp', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b9e\u4e60\u751f,\u5de5\u4f5c\u7ecf\u9a8c\u7684')),
                ('work_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5de5\u4f5c\u6240\u5728\u5730')),
                ('logo', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u516c\u53f8logo')),
                ('homepage', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u516c\u53f8\u5b98\u7f51')),
                ('finacing', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u878d\u8d44\u9636\u6bb5')),
                ('business_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8425\u4e1a\u6267\u7167')),
                ('audit_status', models.IntegerField(default=0, verbose_name='\u662f\u5426\u901a\u8fc7\u5ba1\u6838')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=20, verbose_name='\u8eab\u4efd\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('realname', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='\u7528\u6237\u771f\u5b9e\u59d3\u540d')),
                ('email', models.EmailField(max_length=50, null=True, unique=True, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='\u5bc6\u7801')),
                ('sex', models.IntegerField(choices=[(0, '\u5973'), (1, '\u7537'), (2, '\u4fdd\u5bc6')], default=3, verbose_name='\u6027\u522b')),
                ('totalscore', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7528\u6237\u603b\u5f97\u5206')),
                ('location', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u6240\u5728\u57ce\u5e02')),
                ('intro', models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('is_open', models.IntegerField(choices=[(0, '\u516c\u5f00'), (1, '\u4e0d\u516c\u5f00')], default=0, null=True, verbose_name='\u4e2a\u4eba\u4fe1\u606f\u662f\u5426\u5c55\u793a')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('program_exp', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8ba1\u7b97\u673a\u7f16\u7a0b\u7ecf\u9a8c')),
                ('into_it', models.CharField(blank=True, default=' ', max_length=10, null=True, verbose_name='\u662f\u5426\u4ece\u4e8bIT\u884c\u4e1a')),
                ('comp_use_time_day', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u4f7f\u7528\u7535\u8111\u9891\u7387')),
                ('learn_habit', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u5b66\u4e60\u4e60\u60ef')),
                ('githuburl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='github\u4e3b\u9875')),
                ('linkinurl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='linkin\u4e3b\u9875')),
                ('stackoverflowurl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='stackoverflow\u4e3b\u9875')),
                ('personpage', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u4e2a\u4eba\u4e3b\u9875')),
                ('expect_job', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u671f\u671b\u5de5\u4f5c')),
                ('expect_level', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u671f\u671b\u7ea7\u522b')),
                ('current_company', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u5f53\u524d\u6240\u5728\u516c\u53f8')),
                ('company_location', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u516c\u53f8\u6240\u5728\u5730')),
                ('mugshot', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u5934\u50cfURL')),
                ('mugshotframe', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u753b\u6846URL')),
                ('createtime', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('active', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6fc0\u6d3b\u8d26\u53f7\u7801')),
                ('status', models.IntegerField(default=0, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('pathid', models.IntegerField(default=0, verbose_name='\u6b63\u5728\u8fdb\u884c\u7684\u8def\u5f84ID')),
                ('phone', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='\u516c\u53f8\u7535\u8bdd\u53f7\u7801')),
                ('idcard', models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='\u8eab\u4efd\u8bc1\u56fe\u7247')),
                ('gongpai', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u5de5\u724c\u56fe\u7247')),
                ('on_job_verify', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5728\u804c\u8bc1\u660e')),
                ('joblevel', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='\u5c97\u4f4d\u804c\u79f0')),
                ('companyid', models.IntegerField(blank=True, null=True, verbose_name='\u5173\u8054\u516c\u53f8')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuser.Role')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuser.User', verbose_name='\u7ba1\u7406\u8005\u7684ID'),
        ),
    ]
