# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('realname', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='\u7528\u6237\u771f\u5b9e\u59d3\u540d')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('sex', models.IntegerField(choices=[(0, '\u5973'), (1, '\u7537')], verbose_name='\u6027\u522b')),
                ('totalscore', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7528\u6237\u603b\u5f97\u5206')),
                ('location', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u6240\u5728\u57ce\u5e02')),
                ('intro', models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('is_open', models.IntegerField(choices=[(0, '\u516c\u5f00'), (1, '\u4e0d\u516c\u5f00')], default=0, verbose_name='\u4e2a\u4eba\u4fe1\u606f\u662f\u5426\u5c55\u793a')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('program_exp', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8ba1\u7b97\u673a\u7f16\u7a0b\u7ecf\u9a8c')),
                ('into_it', models.CharField(blank=True, default=' ', max_length=10, null=True, verbose_name='\u662f\u5426\u4ece\u4e8bIT\u884c\u4e1a')),
                ('comp_use_time_day', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u4f7f\u7528\u7535\u8111\u9891\u7387')),
                ('githuburl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='github\u4e3b\u9875')),
                ('linkinurl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='linkin\u4e3b\u9875')),
                ('stackoverflowurl', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='stackoverflow\u4e3b\u9875')),
                ('personpage', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u4e2a\u4eba\u4e3b\u9875')),
                ('expect_job', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u671f\u671b\u5de5\u4f5c')),
                ('expect_level', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u671f\u671b\u7ea7\u522b')),
                ('current_company', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u5f53\u524d\u6240\u5728\u516c\u53f8')),
                ('company_location', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u516c\u53f8\u6240\u5728\u5730')),
                ('mugshot', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u5934\u50cfURL')),
                ('mugshotframe', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u753b\u6846URL')),
            ],
        ),
    ]
