# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0002_auto_20170106_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6fc0\u6d3b\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u662f\u5426\u6fc0\u6d3b'),
        ),
    ]
