# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0003_auto_20170106_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learn_habit',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u5b66\u4e60\u4e60\u60ef'),
        ),
    ]
