# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0004_user_learn_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u5973'), (1, '\u7537'), (2, '\u4fdd\u5bc6')], default=3, verbose_name='\u6027\u522b'),
        ),
    ]
