# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0005_auto_20170106_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='badgeid',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
