# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcourse', '0001_initial'),
        ('vuser', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Course', verbose_name='\u8bfe\u7a0bID'),
        ),
        migrations.AddField(
            model_name='watchrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuser.User', verbose_name='\u7528\u6237ID'),
        ),
        migrations.AddField(
            model_name='watchrecord',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcourse.Video', verbose_name='\u89c6\u9891ID'),
        ),
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcourse.Course', verbose_name='\u8bfe\u7a0bID'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuser.User', verbose_name='\u7528\u6237ID'),
        ),
    ]
