# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgename', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u52cb\u7ae0\u540d\u79f0')),
                ('badgeurl', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u52cb\u7ae0\u56fe\u7247\u4f4d\u7f6e')),
                ('createtime', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='\u52cb\u7ae0\u521b\u5efa\u65f6\u95f4')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Course')),
            ],
        ),
    ]
