# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0006_auto_20170109_0137'),
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_time', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='\u52cb\u7ae0\u83b7\u53d6\u65f6\u95f4')),
                ('badgeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badge.Badge', verbose_name='\u52cb\u7ae0ID')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuser.User', verbose_name='\u7528\u6237ID')),
            ],
        ),
    ]
