# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('desc', models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('totaltime', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8bfe\u7a0b\u603b\u65f6\u957f')),
                ('difficult', models.IntegerField(blank=True, default=4, null=True, verbose_name='\u8bfe\u7a0b\u96be\u5ea6')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u989c\u8272')),
                ('pubstatus', models.IntegerField(choices=[(0, '\u5373\u5c06\u53d1\u5e03'), (1, '\u5df2\u53d1\u5e03'), (2, '\u9ed8\u8ba4')], default=2, null=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('subscibe', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5b66\u4e60\u8bfe\u7a0b\u4eba\u6570')),
                ('order', models.IntegerField(unique=True, verbose_name='\u8bfe\u7a0b\u987a\u5e8f')),
                ('createtime', models.DateTimeField(default=0, verbose_name='\u8bfe\u7a0b\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8def\u7ebf\u540d\u79f0')),
                ('desc', models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='\u8def\u7ebf\u7b80\u4ecb')),
                ('introvideourl', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8def\u7ebf\u4ecb\u7ecd\u89c6\u9891')),
                ('jobscount', models.IntegerField(blank=True, default=5555, null=True, verbose_name='\u5c97\u4f4d\u6570')),
                ('salary', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u5c97\u4f4d\u8d77\u85aa')),
                ('jobtime', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5c97\u4f4d&\u8d77\u85aa\u7edf\u8ba1\u65f6\u95f4')),
                ('difficult', models.IntegerField(blank=True, null=True, verbose_name='\u8def\u5f84\u96be\u5ea6')),
                ('pathimg', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8def\u7ebf\u5c55\u793a\u56fe\u7247')),
                ('totaltime', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8def\u7ebf\u603b\u65f6\u95f4')),
                ('subscibe', models.IntegerField(blank=True, null=True, verbose_name='\u53c2\u52a0\u8def\u7ebf\u4eba\u6570')),
                ('createtime', models.DateTimeField(verbose_name='\u8def\u7ebf\u521b\u5efa\u65f6\u95f4')),
                ('course', models.ManyToManyField(to='vcourse.Course', verbose_name='\u8def\u7ebf\u5305\u542b\u7684\u8bfe\u7a0b')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u5206\u7c7b\u529f\u80fd')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u5206\u7c7b\u6280\u672f')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('videotime', models.IntegerField(verbose_name='\u89c6\u9891\u65f6\u957f')),
                ('video', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u5b58\u653e\u4f4d\u7f6e')),
                ('zimu', models.CharField(max_length=100, verbose_name='\u5b57\u5e55\u5b58\u653e\u4f4d\u7f6e')),
                ('order', models.IntegerField(unique=True, verbose_name='\u89c6\u9891\u64ad\u653e\u987a\u5e8f')),
                ('teacher_note', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8bb2\u5e08\u7b14\u8bb0')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u603b\u8bc4\u661f')),
                ('scorepeople', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8bc4\u661f\u4eba\u6570')),
                ('watchpeople', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u89c2\u770b\u89c6\u9891\u4eba\u6570')),
                ('createtime', models.DateTimeField(verbose_name='\u89c6\u9891\u4e0a\u4f20\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Course', verbose_name='\u8bfe\u7a0bID')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuser.User', verbose_name='\u8bb2\u5e08ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='type_func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcourse.TypeFunc', verbose_name='\u529f\u80fd\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='course',
            name='type_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcourse.TypeProgram', verbose_name='\u8bed\u8a00\u5206\u7c7b'),
        ),
    ]
