# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('desc', models.TextField(blank=True, default=' ', null=True, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('totaltime', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8bfe\u7a0b\u603b\u65f6\u957f')),
                ('difficult', models.IntegerField(blank=True, default=4, null=True, verbose_name='\u8bfe\u7a0b\u96be\u5ea6')),
                ('icon', models.IntegerField(choices=[(0, '\u89c6\u9891'), (1, '\u9898\u5e93'), (2, '\u9879\u76ee')], default=0, verbose_name='\u8bfe\u7a0b\u5bf9\u5e94\u7684\u56fe\u6807')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u989c\u8272')),
                ('pubstatus', models.IntegerField(choices=[(0, '\u5373\u5c06\u53d1\u5e03'), (1, '\u5df2\u53d1\u5e03'), (2, '\u9ed8\u8ba4')], default=2, null=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('subscibe', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5b66\u4e60\u8bfe\u7a0b\u4eba\u6570')),
                ('createtime', models.CharField(max_length=20, verbose_name='\u8bfe\u7a0b\u521b\u5efa\u65f6\u95f4')),
                ('people', models.IntegerField(default=500, verbose_name='\u5b66\u4e60\u8bfe\u7a0b\u7684\u4eba\u6570')),
                ('teach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuser.User', verbose_name='\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8def\u7ebf\u540d\u79f0')),
                ('desc', models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='\u8def\u7ebf\u7b80\u4ecb')),
                ('intrv', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8def\u7ebf\u4ecb\u7ecd\u89c6\u9891')),
                ('jobscount', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='\u5c97\u4f4d\u6570')),
                ('salary', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u5c97\u4f4d\u8d77\u85aa')),
                ('jstime', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5c97\u4f4d&\u8d77\u85aa\u7edf\u8ba1\u65f6\u95f4')),
                ('difficult', models.IntegerField(blank=True, null=True, verbose_name='\u8def\u5f84\u96be\u5ea6')),
                ('pathimg', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8def\u7ebf\u5c55\u793a\u56fe\u7247')),
                ('totaltime', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u8def\u7ebf\u603b\u65f6\u95f4')),
                ('subscibe', models.IntegerField(blank=True, null=True, verbose_name='\u53c2\u52a0\u8def\u7ebf\u4eba\u6570')),
                ('createtime', models.CharField(max_length=20, verbose_name='\u8def\u7ebf\u521b\u5efa\u65f6\u95f4')),
                ('orders', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bfe\u7a0b\u987a\u5e8f')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6280\u672f\u7c7b\u522b')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('vtime', models.IntegerField(verbose_name='\u89c6\u9891\u65f6\u957f')),
                ('vurl', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u5b58\u653e\u4f4d\u7f6e')),
                ('cc', models.CharField(max_length=100, verbose_name='\u5b57\u5e55\u5b58\u653e\u4f4d\u7f6e')),
                ('notes', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u8bb2\u5e08\u7b14\u8bb0')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u603b\u8bc4\u661f')),
                ('scorepeople', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8bc4\u661f\u4eba\u6570')),
                ('watched', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u89c2\u770b\u89c6\u9891\u4eba\u6570')),
                ('createtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u89c6\u9891\u4e0a\u4f20\u65f6\u95f4')),
                ('end', models.IntegerField(default=0, verbose_name='\u662f\u5426\u4e3a\u6700\u540e\u4e00\u8282\u89c6\u9891')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Course', verbose_name='\u8bfe\u7a0bID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcourse.Program', verbose_name='\u6280\u672f\u5206\u7c7b'),
        ),
    ]
