# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='score',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='watchrecord',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='watchrecord',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='watchrecord',
            name='videoid',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='WatchRecord',
        ),
    ]
