# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0002_auto_20170109_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseClass',
            new_name='TypeFunc',
        ),
        migrations.RenameModel(
            old_name='CourseType',
            new_name='TypeProgram',
        ),
    ]
