# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0003_auto_20170109_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cl',
            new_name='type_func',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='type_lang',
        ),
    ]
