# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0005_auto_20170109_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='time',
            new_name='videotime',
        ),
        migrations.AddField(
            model_name='course',
            name='createtime',
            field=models.BigIntegerField(default=0, verbose_name='\u8bfe\u7a0b\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='path',
            name='createtime',
            field=models.BigIntegerField(default=0, verbose_name='\u8def\u7ebf\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='video',
            name='createtime',
            field=models.BigIntegerField(default=0, verbose_name='\u89c6\u9891\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
