# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0006_auto_20170109_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='jobtime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5c97\u4f4d&\u8d77\u85aa\u7edf\u8ba1\u65f6\u95f4'),
        ),
    ]
