# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0007_auto_20170109_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficult',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='\u8bfe\u7a0b\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscibe',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5b66\u4e60\u8bfe\u7a0b\u4eba\u6570'),
        ),
    ]
